/**
 * Simple mandelbrot generator, useful to compare the speed of the ZZ9K (integrated ARM)
 * to that of the native 68k
 */ 
#include <stdint.h>

// Copied from <libraries/Picasso96.h>, not needed when compiling for the 68k
#ifdef ZZ9K_ARM_CODE
/************************************************************************/
/* Types for RGBFormat used
 */
typedef enum {
	RGBFB_NONE,				/* planar mode (the name is historical) */
	RGBFB_CLUT,				/* palette mode, set colors when opening screen using
									tags or use SetRGB32/LoadRGB32(...) */
	RGBFB_R8G8B8,			/* TrueColor RGB (8 bit each) */
	RGBFB_B8G8R8,			/* TrueColor BGR (8 bit each) */
	RGBFB_R5G6B5PC,		/* HiColor16 (5 bit R, 6 bit G, 5 bit B),
									format: gggbbbbbrrrrrggg */
	RGBFB_R5G5B5PC,		/* HiColor15 (5 bit each), format: gggbbbbb0rrrrrgg */
	RGBFB_A8R8G8B8,		/* 4 Byte TrueColor ARGB (A unused alpha channel) */
	RGBFB_A8B8G8R8,		/* 4 Byte TrueColor ABGR (A unused alpha channel) */
	RGBFB_R8G8B8A8,		/* 4 Byte TrueColor RGBA (A unused alpha channel) */
	RGBFB_B8G8R8A8,		/* 4 Byte TrueColor BGRA (A unused alpha channel) */
	RGBFB_R5G6B5,			/* HiColor16 (5 bit R, 6 bit G, 5 bit B),
									format: rrrrrggggggbbbbb */
	RGBFB_R5G5B5,			/* HiColor15 (5 bit each), format: 0rrrrrgggggbbbbb */
	RGBFB_B5G6R5PC,		/* HiColor16 (5 bit R, 6 bit G, 5 bit B),
									format: gggrrrrrbbbbbggg */
	RGBFB_B5G5R5PC,		/* HiColor15 (5 bit each), format: gggrrrrr0bbbbbbgg */

	/* By now, the following formats are for use with a hardware window only
		(bitmap operations may be implemented incompletely) */

	RGBFB_YUV422CGX,		/* 2 Byte TrueColor YUV (CCIR recommendation CCIR601).
									Each two-pixel unit is stored as one longword
									containing luminance (Y) for each of the two pixels,
									and chrominance (U,V) for alternate pixels.
									The missing chrominance values are generated by
									interpolation. (Y0-V0-Y1-U0) */
	RGBFB_YUV411,			/* 1 Byte TrueColor ACCUPAK. Four adjacent pixels form
									a packet of 5 bits Y (luminance) each pixel and 6 bits
									U and V (chrominance) shared by the four pixels */
	RGBFB_YUV411PC,		/* 1 Byte TrueColor ACCUPAK byte swapped (1234 -> 4321) */
	RGBFB_YUV422,			/* 2 Byte TrueColor YUV (CCIR recommendation CCIR601).
									Each two-pixel unit is stored as one longword
									containing luminance (Y) for each of the two pixels,
									and chrominance (U,V) for alternate pixels.
									The missing chrominance values are generated by
									interpolation. (Y1-U0-Y0-V0) */
	RGBFB_YUV422PC,		/* 2 Byte TrueColor CCIR601 byte swapped (V0-Y0-U0-Y1) */
	RGBFB_YUV422PA,		/* 2 Byte TrueColor CCIR601 for use with YUV12 planar
									assist mode on Cirrus Logic base graphics chips.
									(Y0-Y1-V0-U0) */
	RGBFB_YUV422PAPC,		/* 2 Byte TrueColor YUV12 byte swapped (U0-V0-Y1-Y0) */

	RGBFB_MaxFormats
	} RGBFTYPE;

// Assuming 24 bits modes only for simplicity
#define RGBFF_A8R8G8B8			(1<<RGBFB_A8R8G8B8)
#define RGBFF_A8B8G8R8			(1<<RGBFB_A8B8G8R8)
#define RGBFF_R8G8B8A8			(1<<RGBFB_R8G8B8A8)
#define RGBFF_B8G8R8A8			(1<<RGBFB_B8G8R8A8)

#endif

int mandel(uint32_t, uint32_t*);
void setColorShifts(uint32_t, uint8_t*);
